### ISSUE TITLE
ipsec over tcp, pcscf doesnt reply to tcp syn

### ISSUE THREAD

**Issue by pamystri** [herlesupreeth/Kamailio_IMS_Config#5]
Hi Supreeth,

Im trying to set up the open5gs with the Kamailio IMS based on the guide https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/, with real phone and enb, Iam stuck during the 2nd registration phase after the 401 response from PSCSF, 
UE sends tcp syn to the PSCSF ipsec port but with no answer although PSCSF is listening on that port.

I am using  the following
root@open5gs-ims:~# kamailio -v
version: kamailio 5.3.2 (x86_64/linux) 9741e3

I guess you already tested ipsec over tcp, should I upgrade to 5.4 ? 

thanks

**Comment by herlesupreeth** [comment]
can you please send the pcap so that I can help?

**Comment by herlesupreeth** [comment]
btw, which kamailio repo are you using? make sure to take the latest commit from https://github.com/herlesupreeth/kamailio repo, re-compile, install and re-try

**Comment by pamystri** [comment]
hi,
I am using the latest, I will send you the pcap, thanks for the support

**Comment by herlesupreeth** [comment]
Please send the pcap here itself not to my email address.

![image](https://user-images.githubusercontent.com/4115839/97534771-db5f4f00-19ba-11eb-9e5a-71e74c35353c.png)

PCSCF is not responding because you are NATing 10.46.0.23 UE IP with 192.168.250.12 (EPC/PGW) and IMS does not work with NAT in VoLTE scenario. Please remove the iptables rules for NATing and add a static route in IMS VM to find the path back to UE in Downlink i.e. sudo ip r add <UE_IP_SUBNET> via 192.168.250.12.

Just a heads-up, the guide clearly mentions NOT to run EPC and IMS in different machines but you are running EPC/PGW in 192.168.250.12 and IMS/PCSCF in 192.168.250.11, since I dont know your setup completely I am not sure what other issues that may arise

**Comment by pamystri** [comment]
hi,
 
thanks for the support, I installed the upf in the same machine, and now registration is successful,
